[build]
  command = "yarn build"
  functions = "./dist"

#[dev]
#  publish = "./dist"

[[redirects]]
  from="/v1"
  to="/.netlify/functions/notesApi"
  status=200
  force=true

[[redirects]]
  from="/pusher-auth"
  to="/.netlify/functions/pusherAuth"
  status=200
  force=true

