scalar DateTime

input NoteInput 
{
    content: String!
    attachment: String
}

type Note 
{
    noteId: ID!
    content: String
    attachment: String
    createdAt: DateTime!
    updatedAt: DateTime!
    ownerId: ID!
}

type NoteSummary
{
    noteId: ID!
    summary: String
    hasAttachment: Boolean!
    modified: DateTime!
}

extend type Query 
{
    note(noteId: ID!): Note  @authenticated
    notes: [Note]! @authenticated
    recent(max: Int): [NoteSummary]! @authenticated
}

extend type Mutation 
{
    createNote(input: NoteInput): Note @authenticated
    updateNote(noteId: ID!, input: NoteInput): Note @authenticated
    deleteNote(noteId: ID!): Boolean @authenticated
}